export const Types = {
    LOGIN:'LOGIN',
    REGISTER:'REGISTER',
    LOGOUT:'LOGOUT',

    FETCH_STORIES:'FETCH_STORIES',
    FETCH_USERS:'FETCH_USERS',

    UPDATE_STORIES:'UPDATE_STORIES',
    UPDATE_USERS:'UPDATE_USERS'
}